import re
from pathlib import Path


CHAPTERS_DIR = Path("chapters")
TEXTBOOK_DIR = Path("textbook")
INVENTORY_DIR = Path("inventory")
CANDIDATE_RE = re.compile(
    r"^(?:"
    r"\d+\.\d+\s+.+|"
    r"Theorem\s+\d+\.\d+.*|"
    r"Definition\s+\d+\.\d+.*|"
    r"Assumption\s+\d+\.\d+.*|"
    r"Lemma\s+\d+\.\d+.*|"
    r"Corollary\s+\d+\.\d+.*|"
    r"Exercise\s+\d+\.\d+.*"
    r")$"
)


def chapter_number(pdf_path: Path) -> str:
    return pdf_path.name.split("-", maxsplit=1)[0]


def chapter_title(pdf_path: Path) -> str:
    stem = pdf_path.stem
    return stem.split("-", maxsplit=1)[1].replace("-", " ").title()


def excerpt_path(chapter: str) -> Path:
    return TEXTBOOK_DIR / f"ch{chapter}" / f"ch{int(chapter)}_excerpt.txt"


def inventory_path(chapter: str) -> Path:
    return INVENTORY_DIR / f"ch{int(chapter)}-inventory.md"


def candidate_lines(text: str) -> list[str]:
    seen = set()
    candidates = []
    for raw_line in text.splitlines():
        line = " ".join(raw_line.split())
        if line and CANDIDATE_RE.match(line) and line not in seen:
            seen.add(line)
            candidates.append(line)
    return candidates


def inventory_text(pdf_path: Path, chapter: str, candidates: list[str]) -> str:
    rel_pdf = pdf_path.as_posix()
    rel_excerpt = excerpt_path(chapter).as_posix()
    title = chapter_title(pdf_path)
    candidate_block = "\n".join(f"- {line}" for line in candidates[:80])
    if not candidate_block:
        candidate_block = "- No theorem-like headings were detected by the text extractor."

    return f"""# Chapter {int(chapter)} theorem inventory

## Target chapter
- `{rel_pdf}` ({title})

## Source text
- `{rel_excerpt}` is a text extract generated by:
  `uv run python scripts/1_extract_all_chapter_text.py`

## Extracted candidates
{candidate_block}

## First-pass formalization order
1. Review the extracted candidates against the PDF text.
2. Separate deterministic algebra from probability, asymptotic, and distributional statements.
3. Formalize the deterministic algebra first when it can reuse earlier chapter infrastructure.
4. Add the needed measure/probability infrastructure before attempting the main stochastic theorem.

## Status
- not started
"""


def main() -> None:
    INVENTORY_DIR.mkdir(parents=True, exist_ok=True)
    for pdf_path in sorted(CHAPTERS_DIR.glob("[0-9][0-9]-*.pdf")):
        chapter = chapter_number(pdf_path)
        inv_path = inventory_path(chapter)
        if inv_path.exists():
            print(f"skipped {inv_path} (already exists)")
            continue

        text_path = excerpt_path(chapter)
        if not text_path.exists():
            print(f"skipped {inv_path} (missing {text_path})")
            continue

        candidates = candidate_lines(text_path.read_text(encoding="utf-8"))
        inv_path.write_text(inventory_text(pdf_path, chapter, candidates), encoding="utf-8")
        print(f"wrote {inv_path} ({len(candidates)} candidates)")


if __name__ == "__main__":
    main()
